services:
  web:
    container_name: ${ODOO_CONTAINER_NAME}
    image: odoo:${ODOO_VERSION}
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    volumes:
      - ./conf:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ${CUSTOM_ADDONS}:/var/lib/odoo/custom_addons
      - ${ENTERPRISE}:/var/lib/odoo/enterprise
      - ${THEMES}:/var/lib/odoo/themes
  db:
    container_name: ${PG_CONTAINER_NAME}
    image: postgres:${PG_VERSION}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdb-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  pgdb-data: